// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXyboY8PexWWL5cPEtrfCGLjXogyHWjI',
    appId: '1:1051648314525:web:89d8f19fa8bdf278e45874',
    messagingSenderId: '1051648314525',
    projectId: 'home-service-c8284',
    authDomain: 'home-service-c8284.firebaseapp.com',
    storageBucket: 'home-service-c8284.firebasestorage.app',
    measurementId: 'G-0T470M1SR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHa6aNRFIvO1vFJUdwYuDgCJOfmDZcYk',
    appId: '1:1051648314525:android:0698ed8224eff651e45874',
    messagingSenderId: '1051648314525',
    projectId: 'home-service-c8284',
    storageBucket: 'home-service-c8284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LrH0zeeET8WWKjaJiKttvzeFltJp0eI',
    appId: '1:1051648314525:ios:92a0d22fa8a13684e45874',
    messagingSenderId: '1051648314525',
    projectId: 'home-service-c8284',
    storageBucket: 'home-service-c8284.firebasestorage.app',
    iosBundleId: 'com.example.homeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LrH0zeeET8WWKjaJiKttvzeFltJp0eI',
    appId: '1:1051648314525:ios:92a0d22fa8a13684e45874',
    messagingSenderId: '1051648314525',
    projectId: 'home-service-c8284',
    storageBucket: 'home-service-c8284.firebasestorage.app',
    iosBundleId: 'com.example.homeService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbXyboY8PexWWL5cPEtrfCGLjXogyHWjI',
    appId: '1:1051648314525:web:f2ab2ee134a47f11e45874',
    messagingSenderId: '1051648314525',
    projectId: 'home-service-c8284',
    authDomain: 'home-service-c8284.firebaseapp.com',
    storageBucket: 'home-service-c8284.firebasestorage.app',
    measurementId: 'G-PLRBN7Z4EK',
  );
}
